"""Global Application Constants

Defines custom constants and values used throughout the application.
"""

# Username
MAX_USERNAME_LENGTH = 30
MIN_USERNAME_LENGTH = 3

# Email
MIN_EMAIL_LENGTH = 3
MAX_EMAIL_LENGTH = 30

# Password
MIN_PASSWORD_LENGTH = 12
MAX_PASSWORD_LENGTH = 64

# Google
MAX_GOOGLE_ID_LENGTH = 255

# Meeting
MAX_TITLE_LENGTH = 100
MAX_DESCRIPTION_LENGTH = 500
MAX_PARTICIPANT_CAP = 100
MAX_QUESTION_CAP = 50
MEETING_CODE_LENGTH = 8

# Question
MAX_PROMPT_LENGTH = 300
MAX_OPTION_LENGTH = 100
MAX_IDEA_SUBMISSION_LENGTH = 300
MAX_LONG_ANSWER_LENGTH = 500
MAX_RATING_SCALE_VALUE = 10
MIN_RATING_SCALE_VALUE = 0
