"""Add current year and current month field to User object

Revision ID: 200d7b37e8d7
Revises: 076676b48250
Create Date: 2026-07-13 14:13:31.380490

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.sql import text

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "200d7b37e8d7"
down_revision: str | Sequence[str] | None = "076676b48250"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "current_year",
            sa.Integer(),
            nullable=False,
            server_default=text("EXTRACT(YEAR FROM CURRENT_DATE)"),
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "current_month",
            sa.Integer(),
            nullable=False,
            server_default=text("EXTRACT(MONTH FROM CURRENT_DATE)"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "current_month")
    op.drop_column("users", "current_year")
    # ### end Alembic commands ###
