"""Authentication Related Constants

Defines custom constants and values used throughout authentication related endpoints.
"""

import math

TOKEN_HASH_LENGTH_EMAIL_VERIFY = 255

TOKEN_HASH_LENGTH_RESET_PASSWORD_TOKEN = 255

TOKEN_HASH_LENGTH_REFRESH_TOKEN = 255

VERIFY_EMAIL_TOKEN_MAX_DURATION_MINUTES = 60 * 24

VERIFY_EMAIL_TOKEN_COOLDOWN_DURATION_MINUTES = 1

VERIFY_EMAIL_TOKEN_BYTES = 32

VERIFY_EMAIL_TOKEN_LENGTH = math.ceil(VERIFY_EMAIL_TOKEN_BYTES * 4 / 3)
